[[packages]]
versioned_files = ["pyproject.toml"]
changelog = "CHANGELOG.md"

[[workflows]]
name = "task"
    [[workflows.steps]]
    type = "SelectGitHubIssue"

    [[workflows.steps]]
    type = "SwitchBranches"

[[workflows]]
name = "release"
    [[workflows.steps]]
    type = "PrepareRelease"

    [[workflows.steps]]
    type = "Command"
    command = "npx prettier --write CHANGELOG.md"

    [[workflows.steps]]
    type = "Command"
    command = "git add pyproject.toml CHANGELOG.md"

    [[workflows.steps]]
    type = "Command"
    command = "git commit -m \"chore: Bump to version\""
    variables = { "version" = "Version" }

    [[workflows.steps]]
    type = "Command"
    command = "git push"

    [[workflows.steps]]
    type = "Release"

[github]
owner = "openapi-generators"
repo = "openapi-python-client"
