[[workflows]]
name = "task"
    [[workflows.steps]]
    type = "SelectGitHubIssue"

    [[workflows.steps]]
    type = "SwitchBranches"

[[workflows]]
name = "release"
    [[workflows.steps]]
    type = "PrepareRelease"

    [[workflows.steps]]
    type = "Command"
    command = "npx prettier --write CHANGELOG.md"

[github]
owner = "openapi-generators"
repo = "openapi-python-client"
