[project]
name = "my-test-api-client"
version = "0.1.0"
description = "A client library for accessing My Test API"
authors = []
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "tandem-platform",
    "orjson",
    "httpx>=0.23.1,<0.29.0",
    "attrs>=22.2.0",
]

[tool.uv.build-backend]
module-name = "my_test_api_client"
module-root = ""

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "cloudsmith"
url = "https://dl.cloudsmith.io/basic/tandem/artifacts-internal/python/simple/"
publish-url = "https://python.cloudsmith.io/tandem/artifacts-internal/"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "I", "UP"]
