name: Prerelease

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Prerelease label for the release'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: Swatinem/rust-cache@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
      - name: Install Knope
        uses: knope-dev/action@v2.0.0
        with:
          version: 0.11.0
      - name: Bump Version & Create GitHub Release
        run: knope release --prerelease-label="${{ github.event.inputs.label }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Install Poetry
        run: pip install --upgrade poetry
      - name: Push to PyPI
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
