name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@d6f3f49f3345e29369fe57596a3ca8f94c4d2ca7 # v5.4.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
      - name: Install Knope
        uses: knope-dev/action@f694bf4663f7c20743102e732728d676b2ab95db # v1
        with:
          version: 0.6.2
      - name: Bump Version & Create GitHub Release
        run: knope release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Install Poetry
        run: pip install --upgrade poetry
      - name: Push to PyPI
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
